### PR TITLE
Backport multiarch to 0.44

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hadim** [comment]
@scopatz Are you ok merging this in a separate branch (`0.44` for example)?

**Comment by scopatz** [comment]
Having a separate branch won't do anything at the moment, IIRC

**Comment by hadim** [comment]
It won't upload the builds you mean? In that case, can we merge this and I submit a new PR to go back to 0.56?

**Comment by scopatz** [comment]
> It won't upload the builds you mean? In that case, can we merge this and I submit a new PR to go back to 0.56?

Yep, exactly. It won't upload builds.  There is a proposal somewhere to allow building & pushing from multiple branches, but I am not sure it was implemented.

Also, there is no need to go back to 0.56 since that is built now :wink:

**Comment by hadim** [comment]
Yeah, make sense :-D Thanks @scopatz!

**Pull request merged**
