### PR TITLE
Update to 1.2.1

### PR DESCRIPTION
**Pull request by wshanks**

### CODE REVIEW

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by wshanks** [comment]
Hmm, I was playing with using `github.dev` to make the PR -- I seem to have dropped the PR template.

I added myself as a maintainer since it seems like this package hasn't been updated in 9 months.

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
I can't merge this but: it might be worth doing a fresh `grayskull` of this: there's a lot of legacy cruft going on!

**Comment by wshanks** [comment]
Yes, I wish I understood the comment "Cannot be no-arch due to bytecode issues." How can the bytecode be architecture dependent, and why would that only affect this one pure Python package? (@scopatz, any hints?). I wonder if it still holds or if we could just revert to a clean grayskull output.

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by wshanks** [comment]
I reset to grayskull output merged with the non-noarch part of the original recipe. For some reason, re-rendering reverted the license file, so I reverted it back again.

**Comment by bollwyvl** [comment]
It looks like a lot of the ugly junk was removed in the ensuing _many_ versions:

https://github.com/websocket-client/websocket-client/compare/v0.57.0...v1.2.1#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L17

About the only thing that doesn't pass the sniff test for going to `noarch` is the use of `scripts` (vs the better-supported `entry_points`)... I'm not proud, but we do some [stuff over on owrl](https://github.com/conda-forge/owlrl-feedstock/blob/master/recipe/0001-remove-scripts.patch)... but maybe _this_ upstream would accept that change, as it looks like they've made a lot of recent changes to reduce complexity.

**Comment by wshanks** [comment]
Hmm, yes, moving to `entry_points` would be nice. I don't want to prod upstream about that myself though because I don't even use this library directly and there might be some backwards compatibility issues to consider with the change. For me, websocket-client is a dependency of a couple other dependencies I use, including one from conda and one from pip. When the pip dependency gets installed, pip overwrites the lower versioned conda package of websocket-client and that always bugs me.

**Comment by BastianZim** [comment]
Hi @wshanks just to keep you in the loop. I also created a PR here (#42) but for 1.1.0 as I need that version. If that PR gets merged I would merge this one. 
Also, I've added https://github.com/websocket-client/websocket-client/issues/756 upstream, maybe they're willing to switch to `entry_points`.
Hope that's alright!

**Comment by BastianZim** [comment]
#42 has been merged, ready whenever you are.

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by wshanks** [comment]
@BastianZim Nice! I'm glad you were able to get your PR approved.

I rebased my meta.yaml changes on your 1.1 version and am redoing the re-render. If you figure anything out anything about the noarch bytecode issue, please share. I feel like there is a good chance that issue might not be relevant any more and we could switch to noarch, but not knowing exactly what the issue was I am hesitant to change things.

**Comment by wshanks** [comment]
I got confused about the feedstock's license vs the license of the project. Everything should be good now.

**Comment by BastianZim** [comment]
>  If you figure anything out anything about the noarch bytecode issue, please share. I feel like there is a good chance that issue might not be relevant any more and we could switch to noarch, but not knowing exactly what the issue was I am hesitant to change things.

I would agree with you that this is a no-factor now. From what I can find, this was added in https://github.com/conda-forge/websocket-client-feedstock/issues/10 which is not a problem anymore since that line doesn't exist in _setup.py_ anymore and the package is only python3. So once `scripts` is removed upstream, we should be able to switch it back to noarch.

**Comment by BastianZim** [comment]
Hmm, let's see if we can just restart Travis.

**Comment by BastianZim** [comment]
@conda-forge-admin, please restart ci

**Review by BastianZim — APPROVED** [review]

**Pull request merged**
