### PR TITLE
Ticked version, regenerated if needed. (Double-check reqs!)

### PR DESCRIPTION
**Pull request by pmlandwehr**
Made using `tick_my_feedstocks.py`!
- [x] **I have vetted this recipe**

### CODE REVIEW

**Comment by scopatz** [comment]
This is failing on windows.  Probably needs a rerender.

**Comment by scopatz** [comment]
@conda-forge-admin, please rerender

**Comment by pmlandwehr** [comment]
This will need another rerender, when I am in a position to do it.

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by pmlandwehr** [comment]
Is that a magic command? If so I am thrilled.

**Comment by isuruf** [comment]
Yes, see docs, https://conda-forge.org/docs/webservice.html

**Comment by pmlandwehr** [comment]
oh my lord that is amazing.

**Pull request merged**
